spring.application.name=ms-reporting

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/sanos_y_salvos_reporting
spring.data.mongodb.database=sanos_y_salvos_reporting

# Logging
logging.level.cl.duoc.sanosysalvos=DEBUG

# Server Port (To avoid conflicts if running multiple services locally)
server.port=8083
