server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-identity
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
            - id: ms-reporting
              uri: http://localhost:8082
              predicates:
                - Path=/api/reportes/**
            - id: ms-geolocation
              uri: http://localhost:8083
              predicates:
                - Path=/api/geo/**
