spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/sanos_y_salvos_db
spring.datasource.username=Nicolas091109
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update